language: "en"

pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 80
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
policies:
  - name: TEDPolicy
    epochs: 10
    hidden_layers_sizes:
      dialogue: [512, 1024, 512]
      label: [512, 1024, 512]
    number_of_transformer_layers: 4
  - name: MappingPolicy